/**
 * Standard legal disclaimers used across NyayaLens.
 */
export const LEGAL_DISCLAIMERS = {
  generalNotice:
    'NyayaLens AI is an informational tool designed to assist with document comprehension. It does not provide legal advice, does not establish an attorney-client relationship, and is not a substitute for a qualified legal professional.',
  exportNotice:
    'CONFIDENTIAL & INFORMATIONAL ONLY: This brief was generated by NyayaLens AI for document preparation purposes only. It does not constitute formal legal opinion or advice. Verify all terms with a licensed advocate.',
  abstentionNotice:
    'The provided document does not appear to address this question. To avoid hallucination, NyayaLens abstains from answering ungrounded queries.',
  highRiskEscalation:
    'Caution: This document contains high-risk clauses or liability provisions. We strongly advise sharing the generated Lawyer Prep Brief with a qualified advocate before signing or taking action.',
};

/**
 * Validates framing language to ensure AI outputs remain informational.
 *
 * @param text - Text generated by AI
 * @returns Boolean indicating whether output satisfies framing standards
 */
export function validateFramingTone(text: string): boolean {
  const disallowedImperatives = [
    /\byou\s+must\s+sue\b/i,
    /\byou\s+will\s+win\b/i,
    /\bthis\s+is\s+100%\s+illegal\b/i,
    /\bi\s+guarantee\b/i,
    /\bas\s+your\s+attorney\b/i,
  ];

  return !disallowedImperatives.some((pattern) => pattern.test(text));
}
